# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\SOFTWARE\PythonProjects\todoList\interface\about.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(600, 200)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(About.sizePolicy().hasHeightForWidth())
        About.setSizePolicy(sizePolicy)
        About.setMinimumSize(QtCore.QSize(600, 200))
        About.setMaximumSize(QtCore.QSize(600, 200))
        self.gridLayout = QtWidgets.QGridLayout(About)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setObjectName("gridLayout")
        self.Sep2 = QtWidgets.QFrame(About)
        self.Sep2.setFrameShape(QtWidgets.QFrame.HLine)
        self.Sep2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Sep2.setObjectName("Sep2")
        self.gridLayout.addWidget(self.Sep2, 4, 1, 1, 3)
        self.Slogan = QtWidgets.QLabel(About)
        font = QtGui.QFont()
        font.setItalic(True)
        self.Slogan.setFont(font)
        self.Slogan.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Slogan.setObjectName("Slogan")
        self.gridLayout.addWidget(self.Slogan, 5, 0, 1, 1)
        self.OKbt = QtWidgets.QPushButton(About)
        self.OKbt.setObjectName("OKbt")
        self.gridLayout.addWidget(self.OKbt, 5, 3, 1, 1)
        self.Title = QtWidgets.QLabel(About)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Title.setFont(font)
        self.Title.setAlignment(QtCore.Qt.AlignCenter)
        self.Title.setObjectName("Title")
        self.gridLayout.addWidget(self.Title, 0, 1, 1, 3)
        self.Version = QtWidgets.QLabel(About)
        self.Version.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.Version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.Version.setObjectName("Version")
        self.gridLayout.addWidget(self.Version, 1, 2, 1, 2)
        self.Sep1 = QtWidgets.QFrame(About)
        self.Sep1.setFrameShape(QtWidgets.QFrame.HLine)
        self.Sep1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Sep1.setObjectName("Sep1")
        self.gridLayout.addWidget(self.Sep1, 2, 1, 1, 3)
        self.Copyright = QtWidgets.QLabel(About)
        self.Copyright.setObjectName("Copyright")
        self.gridLayout.addWidget(self.Copyright, 1, 1, 1, 1)
        self.Description = QtWidgets.QLabel(About)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Description.setFont(font)
        self.Description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Description.setWordWrap(True)
        self.Description.setObjectName("Description")
        self.gridLayout.addWidget(self.Description, 3, 1, 1, 3)
        spacerItem = QtWidgets.QSpacerItem(309, 29, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 1, 1, 2)
        self.IconGif = QtWidgets.QLabel(About)
        self.IconGif.setMinimumSize(QtCore.QSize(0, 0))
        self.IconGif.setMaximumSize(QtCore.QSize(131, 131))
        font = QtGui.QFont()
        font.setItalic(True)
        self.IconGif.setFont(font)
        self.IconGif.setStyleSheet("background-color: rgba(0, 0, 0, 150)")
        self.IconGif.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.IconGif.setAlignment(QtCore.Qt.AlignCenter)
        self.IconGif.setObjectName("IconGif")
        self.gridLayout.addWidget(self.IconGif, 0, 0, 4, 1)

        self.retranslateUi(About)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About application"))
        self.Slogan.setText(_translate("About", "made for the Hackathon\n"
"event at\n"
"The Programmer Lounge"))
        self.OKbt.setText(_translate("About", "OK"))
        self.Title.setText(_translate("About", "Tickathon"))
        self.Version.setText(_translate("About", "(x64) Version 1.0.0.0"))
        self.Copyright.setText(_translate("About", "Copyright © 2022-2023 MatusGuy"))
        self.Description.setText(_translate("About", "Simple To-do list app."))
        self.IconGif.setText(_translate("About", "tickathon.gif"))
