# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\SOFTWARE\PythonProjects\todoList\interface\activeItems.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToolBox(object):
    def setupUi(self, ToolBox):
        ToolBox.setObjectName("ToolBox")
        ToolBox.resize(400, 300)
        self.Undone = QtWidgets.QWidget()
        self.Undone.setGeometry(QtCore.QRect(0, 0, 400, 246))
        self.Undone.setObjectName("Undone")
        self.gridLayout = QtWidgets.QGridLayout(self.Undone)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.UndoneList = QtWidgets.QListWidget(self.Undone)
        self.UndoneList.setObjectName("UndoneList")
        self.gridLayout.addWidget(self.UndoneList, 0, 0, 1, 1)
        ToolBox.addItem(self.Undone, "")
        self.Done = QtWidgets.QWidget()
        self.Done.setGeometry(QtCore.QRect(0, 0, 400, 246))
        self.Done.setObjectName("Done")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Done)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DoneList = QtWidgets.QListWidget(self.Done)
        self.DoneList.setObjectName("DoneList")
        self.gridLayout_2.addWidget(self.DoneList, 0, 0, 1, 1)
        ToolBox.addItem(self.Done, "")

        self.retranslateUi(ToolBox)
        QtCore.QMetaObject.connectSlotsByName(ToolBox)

    def retranslateUi(self, ToolBox):
        _translate = QtCore.QCoreApplication.translate
        ToolBox.setWindowTitle(_translate("ToolBox", "ToolBox"))
        ToolBox.setItemText(ToolBox.indexOf(self.Undone), _translate("ToolBox", "Unmarked items"))
        ToolBox.setItemText(ToolBox.indexOf(self.Done), _translate("ToolBox", "Marked items"))
