# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\SOFTWARE\Programming\todoList\interface\activeItems.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ToolBox(object):
    def setupUi(self, ToolBox):
        ToolBox.setObjectName("ToolBox")
        ToolBox.resize(400, 300)
        self.Undone = QtWidgets.QWidget()
        self.Undone.setObjectName("Undone")
        self.gridLayout = QtWidgets.QGridLayout(self.Undone)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.UndoneList = QtWidgets.QListWidget(self.Undone)
        self.UndoneList.setObjectName("UndoneList")
        self.gridLayout.addWidget(self.UndoneList, 0, 0, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\SOFTWARE\\Programming\\todoList\\interface\\../assets/uncheckbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToolBox.addItem(self.Undone, icon, "")
        self.Done = QtWidgets.QWidget()
        self.Done.setObjectName("Done")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.Done)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DoneList = QtWidgets.QListWidget(self.Done)
        self.DoneList.setObjectName("DoneList")
        self.gridLayout_2.addWidget(self.DoneList, 0, 0, 1, 1)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\SOFTWARE\\Programming\\todoList\\interface\\../assets/checkbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ToolBox.addItem(self.Done, icon1, "")

        self.retranslateUi(ToolBox)
        QtCore.QMetaObject.connectSlotsByName(ToolBox)

    def retranslateUi(self, ToolBox):
        _translate = QtCore.QCoreApplication.translate
        ToolBox.setWindowTitle(_translate("ToolBox", "ToolBox"))
        ToolBox.setItemText(ToolBox.indexOf(self.Undone), _translate("ToolBox", "Unmarked items"))
        ToolBox.setItemText(ToolBox.indexOf(self.Done), _translate("ToolBox", "Marked items"))
