# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\SOFTWARE\PythonProjects\todoList\interface\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 565)
        self.MainWidget = QtWidgets.QWidget(MainWindow)
        self.MainWidget.setObjectName("MainWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.MainWidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        self.List = QtWidgets.QListWidget(self.MainWidget)
        self.List.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.List.setDragEnabled(True)
        self.List.setDragDropOverwriteMode(True)
        self.List.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.List.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.List.setAlternatingRowColors(False)
        self.List.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.List.setViewMode(QtWidgets.QListView.ListMode)
        self.List.setModelColumn(0)
        self.List.setWordWrap(True)
        self.List.setObjectName("List")
        self.gridLayout.addWidget(self.List, 0, 0, 3, 2)
        self.ControlPanel = QtWidgets.QWidget(self.MainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ControlPanel.sizePolicy().hasHeightForWidth())
        self.ControlPanel.setSizePolicy(sizePolicy)
        self.ControlPanel.setMaximumSize(QtCore.QSize(16777214, 16777215))
        self.ControlPanel.setStyleSheet("QPushButton{\n"
"    image: url()\n"
"}\n"
"\n"
"QPushButton#AddButton:hover{\n"
"    background-color: rgb(85, 255, 0)\n"
"}\n"
"QPushButton#RemoveButton:hover{\n"
"    background-color: rgb(252, 78, 78)\n"
"}\n"
"QPushButton#MarkButton:hover{\n"
"    background-color: rgb(0, 120, 215)\n"
"}")
        self.ControlPanel.setObjectName("ControlPanel")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.ControlPanel)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setContentsMargins(4, 0, 4, 4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.AddButton = QtWidgets.QPushButton(self.ControlPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddButton.sizePolicy().hasHeightForWidth())
        self.AddButton.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("e:\\SOFTWARE\\PythonProjects\\todoList\\interface\\../assets/edit_add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.AddButton.setIcon(icon)
        self.AddButton.setObjectName("AddButton")
        self.verticalLayout.addWidget(self.AddButton)
        self.RemoveButton = QtWidgets.QPushButton(self.ControlPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveButton.sizePolicy().hasHeightForWidth())
        self.RemoveButton.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("e:\\SOFTWARE\\PythonProjects\\todoList\\interface\\../assets/edit_remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RemoveButton.setIcon(icon1)
        self.RemoveButton.setObjectName("RemoveButton")
        self.verticalLayout.addWidget(self.RemoveButton)
        self.MarkButton = QtWidgets.QPushButton(self.ControlPanel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MarkButton.sizePolicy().hasHeightForWidth())
        self.MarkButton.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("e:\\SOFTWARE\\PythonProjects\\todoList\\interface\\../assets/checkbox.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MarkButton.setIcon(icon2)
        self.MarkButton.setObjectName("MarkButton")
        self.verticalLayout.addWidget(self.MarkButton)
        self.gridLayout.addWidget(self.ControlPanel, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.MainWidget)
        self.MenuBar = QtWidgets.QMenuBar(MainWindow)
        self.MenuBar.setGeometry(QtCore.QRect(0, 0, 644, 21))
        self.MenuBar.setObjectName("MenuBar")
        self.menuList = QtWidgets.QMenu(self.MenuBar)
        self.menuList.setObjectName("menuList")
        MainWindow.setMenuBar(self.MenuBar)
        self.StatusBar = QtWidgets.QStatusBar(MainWindow)
        self.StatusBar.setObjectName("StatusBar")
        MainWindow.setStatusBar(self.StatusBar)
        self.AddAction = QtWidgets.QAction(MainWindow)
        self.AddAction.setIcon(icon)
        self.AddAction.setShortcutContext(QtCore.Qt.ApplicationShortcut)
        self.AddAction.setObjectName("AddAction")
        self.RemoveAction = QtWidgets.QAction(MainWindow)
        self.RemoveAction.setIcon(icon1)
        self.RemoveAction.setObjectName("RemoveAction")
        self.MarkAction = QtWidgets.QAction(MainWindow)
        self.MarkAction.setIcon(icon2)
        self.MarkAction.setObjectName("MarkAction")
        self.menuList.addAction(self.AddAction)
        self.menuList.addAction(self.RemoveAction)
        self.menuList.addAction(self.MarkAction)
        self.MenuBar.addAction(self.menuList.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.AddButton.setText(_translate("MainWindow", "Add"))
        self.RemoveButton.setText(_translate("MainWindow", "Remove"))
        self.MarkButton.setText(_translate("MainWindow", "Toggle mark"))
        self.menuList.setTitle(_translate("MainWindow", "List"))
        self.AddAction.setText(_translate("MainWindow", "Add item"))
        self.AddAction.setShortcut(_translate("MainWindow", "F1"))
        self.RemoveAction.setText(_translate("MainWindow", "Remove item"))
        self.RemoveAction.setShortcut(_translate("MainWindow", "F2"))
        self.MarkAction.setText(_translate("MainWindow", "Toggle mark item"))
        self.MarkAction.setToolTip(_translate("MainWindow", "Mark item"))
        self.MarkAction.setShortcut(_translate("MainWindow", "Space"))
